### ISSUE TITLE
Не могу собрать

### ISSUE THREAD

**Issue by Redfern89** [katyo/xr819#1]
root@orangepipcplus:~/xr819__/xradio# make -C /usr/src/linux-headers-5.15.4-sunxi ARCH=arm64 M=/root/xr819__
make: Entering directory '/usr/src/linux-headers-5.15.4-sunxi'

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

make: *** [Makefile:739: include/config/auto.conf] Error 1
make: Leaving directory '/usr/src/linux-headers-5.15.4-sunxi'

**Comment by serhii-nakon** [comment]
https://github.com/fifteenhex/xradio

**Comment by serhii-nakon** [comment]
instruction to build over dkms

apt install linux-headers-armmp-lpae build-essential git dkms -y && \
git clone https://github.com/fifteenhex/xradio.git && \
cd xradio && \
echo 'PACKAGE_NAME=xradio
PACKAGE_VERSION=1.1
MAKE="make -j4 ARCH=arm -C /usr/src/linux-headers-${kernelver} M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build modules"
CLEAN="make -j4 ARCH=arm -C /usr/src/linux-headers-${kernelver} M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build clean"
BUILT_MODULE_NAME=xradio_wlan
DEST_MODULE_LOCATION="/updates"
REMAKE_INITRD=yes
AUTOINSTALL=yes' > dkms.conf && \
dkms add ../xradio && \
dkms build xradio/1.1 && \
dkms install xradio/1.1 && \
mkdir /lib/firmware/xr819 && \
cd /lib/firmware/xr819 && \
wget https://github.com/armbian/firmware/raw/master/xr819/boot_xr819.bin https://github.com/armbian/firmware/raw/master/xr819/fw_xr819.bin https://github.com/armbian/firmware/raw/master/xr819/sdd_xr819.bin && \
cd
